Fix APP_VERSION sed for versioned builds

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,7 +11,6 @@ on:
       - main
       - develop
       - 'feature/**'
-      - 'bugfix/**'
       - 'hotfix/**'
       - 'release/**'
     tags:
@@ -24,9 +23,8 @@ on:
       - './img/**'
       - './Makefile'
     branches:
+      - main
       - develop
-      - 'release/**'
-      - 'hotfix/**'
 
 jobs:
   docker:
@@ -35,6 +33,63 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+name: Docker CI/CD
+
+on:
+  push:
+    paths-ignore:
+      - '**.md'
+      - './docs/**'
+      - './img/**'
+      - './Makefile'
+    branches:
+      - main
+      - develop
+      - 'feature/**'
+      - 'hotfix/**'
+      - 'release/**'
+    tags:
+      - 'v*.*.*'
+
+  pull_request:
+    paths-ignore:
+      - '**.md'
+      - './docs/**'
+      - './img/**'
+      - './Makefile'
+    branches:
+      - main
+      - develop
+
+jobs:
+  docker:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Validate Hotfix Version
+        run: |
+          if [[ "${{ github.ref }}" == refs/heads/hotfix/* ]]; then
+            # Extract the proposed version from the branch name
+            PROPOSED_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/heads/hotfix/v##')
+            
+            # Get the latest tag
+            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
+            
+            # Extract the minor version from the latest tag
+            LATEST_MINOR_VERSION=$(echo $LATEST_TAG | awk -F. '{print $2}')
+            
+            # Extract the minor version from the proposed version
+            PROPOSED_MINOR_VERSION=$(echo $PROPOSED_VERSION | awk -F. '{print $2}')
+            
+            # Validate the minor version
+            if ((PROPOSED_MINOR_VERSION != LATEST_MINOR_VERSION + 1)); then
+              echo "Error: Invalid hotfix version. Minor version should be incremented by 1."
+              exit 1
+            fi
+          fi
+
       - name: Extract Repo Name
         run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/docker-##')" >> $GITHUB_ENV
 
@@ -42,7 +97,6 @@ jobs:
         run: |
           if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             ORIGINAL_BRANCH=${{ github.event.pull_request.head.ref }}
-            # Now, based on ORIGINAL_BRANCH, set APP_VERSION
             case "$ORIGINAL_BRANCH" in
               release/v*)
                 echo "APP_VERSION=$(echo $ORIGINAL_BRANCH | sed -e 's#release/v##')-beta" >> $GITHUB_ENV
@@ -57,7 +111,7 @@ jobs:
           else  # For push events
             case "${{ github.ref }}" in
               refs/tags/*)
-                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/tags/v##')" >> $GITHUB_ENV
+                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##')" >> $GITHUB_ENV
                 ;;
               refs/heads/main)
                 echo "APP_VERSION=latest-alpha" >> $GITHUB_ENV
@@ -67,9 +121,6 @@ jobs:
                 ;;
               refs/heads/feature/*)
                 echo "APP_VERSION=feature-$(echo ${{ github.ref }} | sed -e 's#refs/heads/feature/##')" >> $GITHUB_ENV
-                ;;
-              refs/heads/bugfix/*)
-                echo "APP_VERSION=bugfix-$(echo ${{ github.ref }} | sed -e 's#refs/heads/bugfix/##')" >> $GITHUB_ENV
                 ;;
               refs/heads/hotfix/*)
                 echo "APP_VERSION=hotfix-$(echo ${{ github.ref }} | sed -e 's#refs/heads/hotfix/##')" >> $GITHUB_ENV
@@ -81,7 +132,72 @@ jobs:
                 echo "APP_VERSION=unknown" >> $GITHUB_ENV
                 ;;
             esac
-          fi      
+          fi
+
+      - name: Setup Docker
+        uses: docker/setup-buildx-action@v3
+
+      - name: DockerHub Login
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and Push Docker Image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.APP_VERSION }}
+          labels: |
+            org.opencontainers.image.source=${{ github.event.repository.html_url }}
+          platforms: linux/amd64,linux/arm64
+          build-args: |
+            APP_VERSION=${{ env.APP_VERSION }}
+        
+      - name: Extract Repo Name
+        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/docker-##')" >> $GITHUB_ENV
+
+      - name: Set APP_VERSION
+        run: |
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            ORIGINAL_BRANCH=${{ github.event.pull_request.head.ref }}
+            case "$ORIGINAL_BRANCH" in
+              release/v*)
+                echo "APP_VERSION=$(echo $ORIGINAL_BRANCH | sed -e 's#release/v##')-beta" >> $GITHUB_ENV
+                ;;
+              hotfix/v*)
+                echo "APP_VERSION=$(echo $ORIGINAL_BRANCH | sed -e 's#hotfix/v##')-beta" >> $GITHUB_ENV
+                ;;
+              *)
+                echo "APP_VERSION=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+                ;;
+            esac
+          else  # For push events
+            case "${{ github.ref }}" in
+              refs/tags/*)
+                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##')" >> $GITHUB_ENV
+                ;;
+              refs/heads/main)
+                echo "APP_VERSION=latest-alpha" >> $GITHUB_ENV
+                ;;
+              refs/heads/develop)
+                echo "APP_VERSION=develop" >> $GITHUB_ENV
+                ;;
+              refs/heads/feature/*)
+                echo "APP_VERSION=feature-$(echo ${{ github.ref }} | sed -e 's#refs/heads/feature/##')" >> $GITHUB_ENV
+                ;;
+              refs/heads/hotfix/*)
+                echo "APP_VERSION=hotfix-$(echo ${{ github.ref }} | sed -e 's#refs/heads/hotfix/##')" >> $GITHUB_ENV
+                ;;
+              refs/heads/release/*)
+                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/heads/release/##')-beta" >> $GITHUB_ENV
+                ;;
+              *)
+                echo "APP_VERSION=unknown" >> $GITHUB_ENV
+                ;;
+            esac
+          fi
 
       - name: Setup Docker
         uses: docker/setup-buildx-action@v3
