Add automated versioning

diff --git a/.github/workflows/git-versioning.yml b/.github/workflows/git-versioning.yml
--- a/.github/workflows/git-versioning.yml
+++ b/.github/workflows/git-versioning.yml
@@ -5,77 +5,114 @@ on:
     branches:
       - develop
 
-jobs:
-  versioning_and_merge:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-
-      - name: Get Latest Tag using GitHub API
-        id: get_latest_tag
-        run: |
-          # Use GitHub API to fetch the latest tag and save it to a temporary file for debugging
-          curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
-              -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/${{ github.repository }}/tags" \
-              > /tmp/latest_tag.json
-          
-          # Display the content of the temporary file for debugging
-          cat /tmp/latest_tag.json
-          
-          # Extract the latest tag from the temporary file using jq
-          latest_tag=$(jq -r '.[0].name' /tmp/latest_tag.json)
-          
-          # Parse the MAJOR, MINOR, and PATCH versions from the tag
-          if [[ $latest_tag =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
-            major_version="${BASH_REMATCH[1]}"
-            minor_version="${BASH_REMATCH[2]}"
-            patch_version="${BASH_REMATCH[3]}"
-          else
-            echo "Failed to parse the latest tag version."
-            exit 1
-          fi
+      jobs:
+        versioning_and_merge:
+          runs-on: ubuntu-latest
+          steps:
+            - name: Checkout Code
+              uses: actions/checkout@v4
       
-          echo "major_version=$major_version" >> $GITHUB_ENV
-          echo "minor_version=$minor_version" >> $GITHUB_ENV
-          echo "patch_version=$patch_version" >> $GITHUB_ENV
-        shell: bash      
+            - name: Install jq
+              run: sudo apt-get install -y jq
+      
+            - name: Get Latest Tag using GitHub API
+              id: get_latest_tag
+              run: |
+                # Fetch the latest tag from GitHub API
+                latest_tag=$(curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
+                                 -H "Accept: application/vnd.github.v3+json" \
+                                 "https://api.github.com/repos/${{ github.repository }}/tags" \
+                                 | jq -r '.[0].name')
+                
+                # Log the fetched tag for debugging
+                echo "Latest Tag: $latest_tag"
+      
+                # Parse the MAJOR, MINOR, and PATCH versions from the tag
+                if [[ $latest_tag =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
+                  major_version="${BASH_REMATCH[1]}"
+                  minor_version="${BASH_REMATCH[2]}"
+                  patch_version="${BASH_REMATCH[3]}"
+                else
+                  echo "Failed to parse the latest tag version."
+                  exit 1
+                fi
+      
+                echo "major_version=$major_version" >> $GITHUB_ENV
+                echo "minor_version=$minor_version" >> $GITHUB_ENV
+                echo "patch_version=$patch_version" >> $GITHUB_ENV
+              shell: bash
+      
+# jobs:
+#   versioning_and_merge:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
 
-      - name: Get Latest Commit Message
-        id: get_latest_commit
-        run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
-        shell: bash
+#       - name: Get Latest Tag using GitHub API
+#         id: get_latest_tag
+#         run: |
+#           # Use GitHub API to fetch the latest tag and save it to a temporary file for debugging
+#           curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
+#               -H "Accept: application/vnd.github.v3+json" \
+#               "https://api.github.com/repos/${{ github.repository }}/tags" \
+#               > /tmp/latest_tag.json
+          
+#           # Display the content of the temporary file for debugging
+#           cat /tmp/latest_tag.json
+          
+#           # Extract the latest tag from the temporary file using jq
+#           latest_tag=$(jq -r '.[0].name' /tmp/latest_tag.json)
+          
+#           # Parse the MAJOR, MINOR, and PATCH versions from the tag
+#           if [[ $latest_tag =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
+#             major_version="${BASH_REMATCH[1]}"
+#             minor_version="${BASH_REMATCH[2]}"
+#             patch_version="${BASH_REMATCH[3]}"
+#           else
+#             echo "Failed to parse the latest tag version."
+#             exit 1
+#           fi
+      
+#           echo "major_version=$major_version" >> $GITHUB_ENV
+#           echo "minor_version=$minor_version" >> $GITHUB_ENV
+#           echo "patch_version=$patch_version" >> $GITHUB_ENV
+#         shell: bash      
 
-      - name: Calculate Version
-        id: calculate_version
-        run: |
-          latest_commit_message=${{ env.commit_message }}
+#       - name: Get Latest Commit Message
+#         id: get_latest_commit
+#         run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
+#         shell: bash
 
-          # Increment MAJOR version if latest commit message contains "do-major-update"
-          if [[ "$latest_commit_message" == *"do-major-update"* ]]; then
-            ((MAJOR++))
-          fi
+#       - name: Calculate Version
+#         id: calculate_version
+#         run: |
+#           latest_commit_message=${{ env.commit_message }}
 
-          # Calculate the number of merged feature PRs since the last tag
-          MINOR_ADD=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=%B | grep -o 'Merge pull request' | grep -c 'feature')
+#           # Increment MAJOR version if latest commit message contains "do-major-update"
+#           if [[ "$latest_commit_message" == *"do-major-update"* ]]; then
+#             ((MAJOR++))
+#           fi
 
-          # Calculate the number of merged bugfix PRs since the last tag
-          PATCH_ADD=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=%B | grep -o 'Merge pull request' | grep -c 'bugfix')
+#           # Calculate the number of merged feature PRs since the last tag
+#           MINOR_ADD=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=%B | grep -o 'Merge pull request' | grep -c 'feature')
 
-          # Increment MINOR and PATCH based on these numbers
-          ((MINOR+=MINOR_ADD))
-          ((PATCH+=PATCH_ADD))
+#           # Calculate the number of merged bugfix PRs since the last tag
+#           PATCH_ADD=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=%B | grep -o 'Merge pull request' | grep -c 'bugfix')
 
-          # Set the new version using the GitHub API
-          token="${{ secrets.MY_GITHUB_TOKEN }}"
-          repo="${{ github.repository }}"
-          new_version="v$MAJOR.$MINOR.$PATCH"
-          url="https://api.github.com/repos/$repo/actions/workflows/$GITHUB_RUN_ID/dispatches"
+#           # Increment MINOR and PATCH based on these numbers
+#           ((MINOR+=MINOR_ADD))
+#           ((PATCH+=PATCH_ADD))
 
-          payload="{\"ref\":\"$GITHUB_REF\",\"inputs\":{\"new_version\":\"$new_version\"}}"
+#           # Set the new version using the GitHub API
+#           token="${{ secrets.MY_GITHUB_TOKEN }}"
+#           repo="${{ github.repository }}"
+#           new_version="v$MAJOR.$MINOR.$PATCH"
+#           url="https://api.github.com/repos/$repo/actions/workflows/$GITHUB_RUN_ID/dispatches"
 
-          curl -X POST -H "Authorization: token $token" -H "Accept: application/vnd.github.v3+json" -d "$payload" "$url"
+#           payload="{\"ref\":\"$GITHUB_REF\",\"inputs\":{\"new_version\":\"$new_version\"}}"
 
-        shell: bash
+#           curl -X POST -H "Authorization: token $token" -H "Accept: application/vnd.github.v3+json" -d "$payload" "$url"
+
+#         shell: bash
 
